import 'package:flutter/material.dart';
import 'package:flutterapp/comeonapp/generatedcafemochawidget2/generated/GeneratedCaffMochaWidget.dart';
import 'package:flutterapp/comeonapp/generatedcafemochawidget2/generated/GeneratedCafemochaWidget3.dart';
import 'package:flutterapp/comeonapp/generatedcafemochawidget2/generated/GeneratedCoffeebackgroundWidget8.dart';
import 'package:flutterapp/comeonapp/generatedcafemochawidget2/generated/GeneratedOurrichfullbodiedespressocombinedwithbittersweetmochasa.dart';
import 'package:flutterapp/comeonapp/generatedcafemochawidget2/generated/GeneratedPriceWidget6.dart';
import 'package:flutterapp/comeonapp/generatedcafemochawidget2/generated/GeneratedBackWidget14.dart';
import 'package:flutterapp/comeonapp/generatedcafemochawidget2/generated/GeneratedAddToBuyWidget6.dart';
import 'package:flutterapp/comeonapp/generatedcafemochawidget2/generated/GeneratedLine8Widget5.dart';
import 'package:flutterapp/comeonapp/generatedcafemochawidget2/generated/Generated119Widget2.dart';
import 'package:flutterapp/comeonapp/generatedcafemochawidget2/generated/GeneratedLine7Widget5.dart';
import 'package:flutterapp/comeonapp/generatedcafemochawidget2/generated/GeneratedWhitesymbolsWidget7.dart';
import 'package:flutterapp/comeonapp/generatedcafemochawidget2/generated/GeneratedWhiterectangletopWidget6.dart';
import 'package:flutterapp/comeonapp/generatedcafemochawidget2/generated/GeneratedRectangle1Widget6.dart';
import 'package:flutterapp/comeonapp/generatedcafemochawidget2/generated/GeneratedCoffeemainlogoWidget8.dart';
import 'package:flutterapp/comeonapp/generatedcafemochawidget2/generated/GeneratedBackWidget15.dart';
import 'package:flutterapp/comeonapp/generatedcafemochawidget2/generated/GeneratedBrownrectangleWidget7.dart';
import 'package:flutterapp/comeonapp/generatedcafemochawidget2/generated/GeneratedRectangle2Widget6.dart';

/* Frame cafe mocha
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCafemochaWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1360.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 896.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -270.0,
                              top: 162.0,
                              right: null,
                              bottom: null,
                              width: 1080.0,
                              height: 887.0,
                              child: GeneratedCoffeebackgroundWidget8(),
                            ),
                            Positioned(
                              left: -260.0,
                              top: 1348.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 12.0,
                              child: GeneratedBackWidget14(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 730.0,
                              right: null,
                              bottom: null,
                              width: 256.0,
                              height: 37.0,
                              child: GeneratedRectangle1Widget6(),
                            ),
                            Positioned(
                              left: 131.0,
                              top: 740.0,
                              right: null,
                              bottom: null,
                              width: 154.0,
                              height: 18.0,
                              child: GeneratedAddToBuyWidget6(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -165.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 309.0,
                              child: GeneratedBrownrectangleWidget7(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: -5.0,
                              right: null,
                              bottom: null,
                              width: 0.0,
                              height: 0.0,
                              child: GeneratedWhitesymbolsWidget7(),
                            ),
                            Positioned(
                              left: -6.0,
                              top: 19.0,
                              right: null,
                              bottom: null,
                              width: 421.0,
                              height: 1.0,
                              child: GeneratedLine7Widget5(),
                            ),
                            Positioned(
                              left: -5.0,
                              top: 9.0,
                              right: null,
                              bottom: null,
                              width: 424.0,
                              height: 1.0,
                              child: GeneratedLine8Widget5(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 111.0,
                              right: null,
                              bottom: null,
                              width: 325.0,
                              height: 598.0,
                              child: GeneratedWhiterectangletopWidget6(),
                            ),
                            Positioned(
                              left: 155.0,
                              top: 592.0,
                              right: null,
                              bottom: null,
                              width: 111.0,
                              height: 57.0,
                              child: Generated119Widget2(),
                            ),
                            Positioned(
                              left: 131.0,
                              top: 577.0,
                              right: null,
                              bottom: null,
                              width: 152.0,
                              height: 71.0,
                              child: GeneratedRectangle2Widget6(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 584.0,
                              right: null,
                              bottom: null,
                              width: 51.0,
                              height: 18.0,
                              child: GeneratedPriceWidget6(),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 477.0,
                              right: null,
                              bottom: null,
                              width: 326.0,
                              height: 77.0,
                              child:
                                  GeneratedOurrichfullbodiedespressocombinedwithbittersweetmochasa(),
                            ),
                            Positioned(
                              left: 105.0,
                              top: 410.0,
                              right: null,
                              bottom: null,
                              width: 214.0,
                              height: 23.0,
                              child: GeneratedCaffMochaWidget(),
                            ),
                            Positioned(
                              left: 10.0,
                              top: 29.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 12.0,
                              child: GeneratedBackWidget15(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: -48.0,
                              right: null,
                              bottom: null,
                              width: 274.0,
                              height: 274.0,
                              child: GeneratedCoffeemainlogoWidget8(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 145.0,
                              right: null,
                              bottom: null,
                              width: 256.0,
                              height: 250.0,
                              child: GeneratedCafemochaWidget3(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
