import 'package:flutter/material.dart';
import 'package:flutterapp/comeonapp/generatedamericanowidget/generated/GeneratedLine5Widget1.dart';
import 'package:flutterapp/comeonapp/generatedamericanowidget/generated/GeneratedAmericano2Widget.dart';
import 'package:flutterapp/comeonapp/generatedamericanowidget/generated/GeneratedEspressoshotstoppedwithhotwatercreatealightlayerofcrema.dart';
import 'package:flutterapp/comeonapp/generatedamericanowidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/comeonapp/generatedamericanowidget/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/comeonapp/generatedamericanowidget/generated/GeneratedCoffeebackgroundWidget2.dart';
import 'package:flutterapp/comeonapp/generatedamericanowidget/generated/GeneratedBackWidget2.dart';
import 'package:flutterapp/comeonapp/generatedamericanowidget/generated/GeneratedLine6Widget1.dart';
import 'package:flutterapp/comeonapp/generatedamericanowidget/generated/GeneratedBackWidget3.dart';
import 'package:flutterapp/comeonapp/generatedamericanowidget/generated/GeneratedWhiterectangletopWidget.dart';
import 'package:flutterapp/comeonapp/generatedamericanowidget/generated/GeneratedCoffeemainlogoWidget2.dart';
import 'package:flutterapp/comeonapp/generatedamericanowidget/generated/GeneratedWhitesymbolsWidget1.dart';
import 'package:flutterapp/comeonapp/generatedamericanowidget/generated/GeneratedBrownrectangleWidget1.dart';
import 'package:flutterapp/comeonapp/generatedamericanowidget/generated/GeneratedAmericanoWidget1.dart';
import 'package:flutterapp/comeonapp/generatedamericanowidget/generated/Generated119Widget1.dart';
import 'package:flutterapp/comeonapp/generatedamericanowidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/comeonapp/generatedamericanowidget/generated/GeneratedPriceWidget.dart';

/* Frame Americano
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAmericanoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1360.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 896.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -270.0,
                              top: 162.0,
                              right: null,
                              bottom: null,
                              width: 1080.0,
                              height: 887.0,
                              child: GeneratedCoffeebackgroundWidget2(),
                            ),
                            Positioned(
                              left: -260.0,
                              top: 1348.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 12.0,
                              child: GeneratedBackWidget2(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 730.0,
                              right: null,
                              bottom: null,
                              width: 256.0,
                              height: 37.0,
                              child: GeneratedRectangle1Widget(),
                            ),
                            Positioned(
                              left: 131.0,
                              top: 740.0,
                              right: null,
                              bottom: null,
                              width: 152.0,
                              height: 16.0,
                              child: GeneratedFrame1Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -165.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 309.0,
                              child: GeneratedBrownrectangleWidget1(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: -3.0,
                              right: null,
                              bottom: null,
                              width: 0.0,
                              height: 0.0,
                              child: GeneratedWhitesymbolsWidget1(),
                            ),
                            Positioned(
                              left: -6.0,
                              top: 20.0,
                              right: null,
                              bottom: null,
                              width: 421.0,
                              height: 1.0,
                              child: GeneratedLine5Widget1(),
                            ),
                            Positioned(
                              left: -5.0,
                              top: 10.0,
                              right: null,
                              bottom: null,
                              width: 424.0,
                              height: 1.0,
                              child: GeneratedLine6Widget1(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 111.0,
                              right: null,
                              bottom: null,
                              width: 325.0,
                              height: 598.0,
                              child: GeneratedWhiterectangletopWidget(),
                            ),
                            Positioned(
                              left: 131.0,
                              top: 577.0,
                              right: null,
                              bottom: null,
                              width: 152.0,
                              height: 71.0,
                              child: GeneratedRectangle2Widget(),
                            ),
                            Positioned(
                              left: 154.0,
                              top: 593.0,
                              right: null,
                              bottom: null,
                              width: 111.0,
                              height: 57.0,
                              child: Generated119Widget1(),
                            ),
                            Positioned(
                              left: 156.0,
                              top: 583.0,
                              right: null,
                              bottom: null,
                              width: 51.0,
                              height: 18.0,
                              child: GeneratedPriceWidget(),
                            ),
                            Positioned(
                              left: 335.0,
                              top: 145.0,
                              right: null,
                              bottom: null,
                              width: 256.0,
                              height: 248.0,
                              child: GeneratedAmericano2Widget(),
                            ),
                            Positioned(
                              left: 55.0,
                              top: 470.0,
                              right: null,
                              bottom: null,
                              width: 316.0,
                              height: 77.0,
                              child:
                                  GeneratedEspressoshotstoppedwithhotwatercreatealightlayerofcrema(),
                            ),
                            Positioned(
                              left: 121.0,
                              top: 412.0,
                              right: null,
                              bottom: null,
                              width: 177.0,
                              height: 26.0,
                              child: GeneratedAmericanoWidget1(),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 35.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 12.0,
                              child: GeneratedBackWidget3(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: -48.0,
                              right: null,
                              bottom: null,
                              width: 274.0,
                              height: 274.0,
                              child: GeneratedCoffeemainlogoWidget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
