import 'package:flutter/material.dart';
import 'package:flutterapp/comeonapp/generatedorderreceivedwidget/generated/GeneratedBrownrectangleWidget10.dart';
import 'package:flutterapp/comeonapp/generatedorderreceivedwidget/generated/GeneratedLeftrectangleWidget.dart';
import 'package:flutterapp/comeonapp/generatedorderreceivedwidget/generated/GeneratedWhitesymbolsWidget11.dart';
import 'package:flutterapp/comeonapp/generatedorderreceivedwidget/generated/GeneratedOrderReceivedWidget.dart';
import 'package:flutterapp/comeonapp/generatedorderreceivedwidget/generated/GeneratedBrowntick21Widget.dart';
import 'package:flutterapp/comeonapp/generatedorderreceivedwidget/generated/GeneratedYourOrderwasplacedsuccessfullyWidget.dart';
import 'package:flutterapp/comeonapp/generatedorderreceivedwidget/generated/GeneratedHomeWidget.dart';
import 'package:flutterapp/comeonapp/generatedorderreceivedwidget/generated/GeneratedLine14Widget.dart';
import 'package:flutterapp/comeonapp/generatedorderreceivedwidget/generated/GeneratedLine13Widget.dart';
import 'package:flutterapp/comeonapp/generatedorderreceivedwidget/generated/GeneratedCoffeebackgroundWidget12.dart';

/* Frame order received
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOrderreceivedWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1049.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 896.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -270.0,
                              top: 162.0,
                              right: null,
                              bottom: null,
                              width: 1080.0,
                              height: 887.0,
                              child: GeneratedCoffeebackgroundWidget12(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -165.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 1085.0,
                              child: GeneratedBrownrectangleWidget10(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: -3.0,
                              right: null,
                              bottom: null,
                              width: 0.0,
                              height: 0.0,
                              child: GeneratedWhitesymbolsWidget11(),
                            ),
                            Positioned(
                              left: 137.0,
                              top: 762.0,
                              right: null,
                              bottom: null,
                              width: 139.0,
                              height: 43.0,
                              child: GeneratedLeftrectangleWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 21.0,
                              right: null,
                              bottom: null,
                              width: 421.0,
                              height: 1.0,
                              child: GeneratedLine13Widget(),
                            ),
                            Positioned(
                              left: 1.0,
                              top: 11.0,
                              right: null,
                              bottom: null,
                              width: 424.0,
                              height: 1.0,
                              child: GeneratedLine14Widget(),
                            ),
                            Positioned(
                              left: 180.0,
                              top: 777.0,
                              right: null,
                              bottom: null,
                              width: 58.0,
                              height: 18.0,
                              child: GeneratedHomeWidget(),
                            ),
                            Positioned(
                              left: 109.0,
                              top: 162.0,
                              right: null,
                              bottom: null,
                              width: 192.0,
                              height: 198.0,
                              child: GeneratedBrowntick21Widget(),
                            ),
                            Positioned(
                              left: 125.0,
                              top: 438.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 27.0,
                              child: GeneratedOrderReceivedWidget(),
                            ),
                            Positioned(
                              left: 61.0,
                              top: 463.0,
                              right: null,
                              bottom: null,
                              width: 305.0,
                              height: 21.0,
                              child:
                                  GeneratedYourOrderwasplacedsuccessfullyWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
