import 'package:flutter/material.dart';
import 'package:flutterapp/comeonapp/generatedorganiccoffeewidget/generated/GeneratedAddToBuyWidget8.dart';
import 'package:flutterapp/comeonapp/generatedorganiccoffeewidget/generated/GeneratedBackWidget19.dart';
import 'package:flutterapp/comeonapp/generatedorganiccoffeewidget/generated/GeneratedCoffeemainlogoWidget10.dart';
import 'package:flutterapp/comeonapp/generatedorganiccoffeewidget/generated/GeneratedLine7Widget7.dart';
import 'package:flutterapp/comeonapp/generatedorganiccoffeewidget/generated/GeneratedOrganicwholebeancoffeeeachcupisanenticingandexoticadven.dart';
import 'package:flutterapp/comeonapp/generatedorganiccoffeewidget/generated/GeneratedWhiterectangletopWidget8.dart';
import 'package:flutterapp/comeonapp/generatedorganiccoffeewidget/generated/GeneratedOrganicCoffeeWidget.dart';
import 'package:flutterapp/comeonapp/generatedorganiccoffeewidget/generated/GeneratedBackWidget18.dart';
import 'package:flutterapp/comeonapp/generatedorganiccoffeewidget/generated/GeneratedOrganiccoffee1Widget.dart';
import 'package:flutterapp/comeonapp/generatedorganiccoffeewidget/generated/GeneratedBrownrectangleWidget9.dart';
import 'package:flutterapp/comeonapp/generatedorganiccoffeewidget/generated/GeneratedWhitesymbolsWidget9.dart';
import 'package:flutterapp/comeonapp/generatedorganiccoffeewidget/generated/GeneratedCoffeebackgroundWidget10.dart';
import 'package:flutterapp/comeonapp/generatedorganiccoffeewidget/generated/GeneratedPriceWidget8.dart';
import 'package:flutterapp/comeonapp/generatedorganiccoffeewidget/generated/GeneratedRectangle2Widget8.dart';
import 'package:flutterapp/comeonapp/generatedorganiccoffeewidget/generated/Generated79Widget.dart';
import 'package:flutterapp/comeonapp/generatedorganiccoffeewidget/generated/GeneratedRectangle1Widget8.dart';
import 'package:flutterapp/comeonapp/generatedorganiccoffeewidget/generated/GeneratedLine8Widget7.dart';

/* Frame organic coffee
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOrganiccoffeeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1360.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 896.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -270.0,
                              top: 162.0,
                              right: null,
                              bottom: null,
                              width: 1080.0,
                              height: 887.0,
                              child: GeneratedCoffeebackgroundWidget10(),
                            ),
                            Positioned(
                              left: -260.0,
                              top: 1348.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 12.0,
                              child: GeneratedBackWidget18(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 730.0,
                              right: null,
                              bottom: null,
                              width: 256.0,
                              height: 37.0,
                              child: GeneratedRectangle1Widget8(),
                            ),
                            Positioned(
                              left: 131.0,
                              top: 740.0,
                              right: null,
                              bottom: null,
                              width: 154.0,
                              height: 18.0,
                              child: GeneratedAddToBuyWidget8(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -165.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 309.0,
                              child: GeneratedBrownrectangleWidget9(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: -5.0,
                              right: null,
                              bottom: null,
                              width: 0.0,
                              height: 0.0,
                              child: GeneratedWhitesymbolsWidget9(),
                            ),
                            Positioned(
                              left: -6.0,
                              top: 19.0,
                              right: null,
                              bottom: null,
                              width: 421.0,
                              height: 1.0,
                              child: GeneratedLine7Widget7(),
                            ),
                            Positioned(
                              left: -5.0,
                              top: 9.0,
                              right: null,
                              bottom: null,
                              width: 424.0,
                              height: 1.0,
                              child: GeneratedLine8Widget7(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 111.0,
                              right: null,
                              bottom: null,
                              width: 325.0,
                              height: 598.0,
                              child: GeneratedWhiterectangletopWidget8(),
                            ),
                            Positioned(
                              left: 170.0,
                              top: 592.0,
                              right: null,
                              bottom: null,
                              width: 84.0,
                              height: 57.0,
                              child: Generated79Widget(),
                            ),
                            Positioned(
                              left: 131.0,
                              top: 577.0,
                              right: null,
                              bottom: null,
                              width: 152.0,
                              height: 71.0,
                              child: GeneratedRectangle2Widget8(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 584.0,
                              right: null,
                              bottom: null,
                              width: 51.0,
                              height: 18.0,
                              child: GeneratedPriceWidget8(),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 477.0,
                              right: null,
                              bottom: null,
                              width: 326.0,
                              height: 47.0,
                              child:
                                  GeneratedOrganicwholebeancoffeeeachcupisanenticingandexoticadven(),
                            ),
                            Positioned(
                              left: 69.0,
                              top: 410.0,
                              right: null,
                              bottom: null,
                              width: 275.0,
                              height: 23.0,
                              child: GeneratedOrganicCoffeeWidget(),
                            ),
                            Positioned(
                              left: 10.0,
                              top: 29.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 12.0,
                              child: GeneratedBackWidget19(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: -48.0,
                              right: null,
                              bottom: null,
                              width: 274.0,
                              height: 274.0,
                              child: GeneratedCoffeemainlogoWidget10(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 145.0,
                              right: null,
                              bottom: null,
                              width: 254.0,
                              height: 250.0,
                              child: GeneratedOrganiccoffee1Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
