import 'package:flutter/material.dart';
import 'package:flutterapp/comeonapp/generatedfourthpagewidget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/comeonapp/generatedfourthpagewidget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/comeonapp/generatedfourthpagewidget/generated/GeneratedPAYWidget.dart';
import 'package:flutterapp/comeonapp/generatedfourthpagewidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/comeonapp/generatedfourthpagewidget/generated/GeneratedLATTEPAYWidget.dart';
import 'package:flutterapp/comeonapp/generatedfourthpagewidget/generated/GeneratedDELIVERYADDRESSWidget.dart';
import 'package:flutterapp/comeonapp/generatedfourthpagewidget/generated/GeneratedPAYMENTMETHODWidget.dart';
import 'package:flutterapp/comeonapp/generatedfourthpagewidget/generated/GeneratedCREDITDEBITCARDWidget.dart';
import 'package:flutterapp/comeonapp/generatedfourthpagewidget/generated/GeneratedCoffeemainlogoWidget13.dart';
import 'package:flutterapp/comeonapp/generatedfourthpagewidget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/comeonapp/generatedfourthpagewidget/generated/GeneratedADDRESSS1Widget.dart';
import 'package:flutterapp/comeonapp/generatedfourthpagewidget/generated/GeneratedCheckoutWidget1.dart';
import 'package:flutterapp/comeonapp/generatedfourthpagewidget/generated/GeneratedBrownrectangleWidget12.dart';
import 'package:flutterapp/comeonapp/generatedfourthpagewidget/generated/GeneratedNETBANKINGWidget.dart';
import 'package:flutterapp/comeonapp/generatedfourthpagewidget/generated/GeneratedRectangle4Widget.dart';

/* Frame fourth page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFourthpageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 32.0,
                top: 219.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 38.0,
                child: GeneratedDELIVERYADDRESSWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 255.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 88.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 646.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 88.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 88.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 88.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 378.0,
                height: 38.0,
                child: GeneratedPAYMENTMETHODWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 266.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 15.0,
                child: GeneratedADDRESSS1Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 211.0,
                height: 13.0,
                child: GeneratedCREDITDEBITCARDWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 536.0,
                right: null,
                bottom: null,
                width: 171.0,
                height: 16.0,
                child: GeneratedNETBANKINGWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 652.0,
                right: null,
                bottom: null,
                width: 154.0,
                height: 13.0,
                child: GeneratedLATTEPAYWidget(),
              ),
              Positioned(
                left: 105.0,
                top: 758.0,
                right: null,
                bottom: null,
                width: 203.0,
                height: 38.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 136.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 26.0,
                child: GeneratedPAYWidget(),
              ),
              Positioned(
                left: 0.0,
                top: -165.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 350.0,
                child: GeneratedBrownrectangleWidget12(),
              ),
              Positioned(
                left: 70.0,
                top: -48.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 274.0,
                child: GeneratedCoffeemainlogoWidget13(),
              ),
              Positioned(
                left: 132.0,
                top: 102.0,
                right: null,
                bottom: null,
                width: 154.0,
                height: 33.0,
                child: GeneratedCheckoutWidget1(),
              )
            ]),
      ),
    ));
  }
}
