import 'package:flutter/material.dart';
import 'package:flutterapp/comeonapp/generatedsecondpagewidget/generated/GeneratedCafemochaWidget.dart';
import 'package:flutterapp/comeonapp/generatedsecondpagewidget/generated/Generated12Widget.dart';
import 'package:flutterapp/comeonapp/generatedsecondpagewidget/generated/GeneratedBackWidget.dart';
import 'package:flutterapp/comeonapp/generatedsecondpagewidget/generated/GeneratedViewOrderSummaryWidget.dart';
import 'package:flutterapp/comeonapp/generatedsecondpagewidget/generated/GeneratedWhitesymbolsWidget.dart';
import 'package:flutterapp/comeonapp/generatedsecondpagewidget/generated/GeneratedCoffeebackgroundWidget1.dart';
import 'package:flutterapp/comeonapp/generatedsecondpagewidget/generated/GeneratedAMERICANOWidget.dart';
import 'package:flutterapp/comeonapp/generatedsecondpagewidget/generated/GeneratedLine5Widget.dart';
import 'package:flutterapp/comeonapp/generatedsecondpagewidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/comeonapp/generatedsecondpagewidget/generated/GeneratedCafelatteWidget.dart';
import 'package:flutterapp/comeonapp/generatedsecondpagewidget/generated/GeneratedESPRESSOWidget.dart';
import 'package:flutterapp/comeonapp/generatedsecondpagewidget/generated/GeneratedLine15Widget.dart';
import 'package:flutterapp/comeonapp/generatedsecondpagewidget/generated/GeneratedGroup2Widget.dart';
import 'package:flutterapp/comeonapp/generatedsecondpagewidget/generated/GeneratedLine16Widget.dart';
import 'package:flutterapp/comeonapp/generatedsecondpagewidget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/comeonapp/generatedsecondpagewidget/generated/GeneratedPIZZAWidget.dart';
import 'package:flutterapp/comeonapp/generatedsecondpagewidget/generated/GeneratedMenuWidget.dart';
import 'package:flutterapp/comeonapp/generatedsecondpagewidget/generated/GeneratedCoffeemainlogoWidget1.dart';
import 'package:flutterapp/comeonapp/generatedsecondpagewidget/generated/GeneratedBackWidget1.dart';

/* Frame Second page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSecondpageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1360.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 896.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 301.0,
                              top: 149.0,
                              right: null,
                              bottom: null,
                              width: 82.0,
                              height: 18.0,
                              child: GeneratedGroup2Widget(),
                            ),
                            Positioned(
                              left: 294.0,
                              top: 162.0,
                              right: null,
                              bottom: null,
                              width: 89.0,
                              height: 1.0,
                              child: GeneratedLine16Widget(),
                            ),
                            Positioned(
                              left: -246.0,
                              top: 154.0,
                              right: null,
                              bottom: null,
                              width: 1080.0,
                              height: 693.0,
                              child: GeneratedCoffeebackgroundWidget1(),
                            ),
                            Positioned(
                              left: -260.0,
                              top: 1348.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 12.0,
                              child: GeneratedBackWidget(),
                            ),
                            Positioned(
                              left: 3.0,
                              top: 436.0,
                              right: null,
                              bottom: null,
                              width: 395.0,
                              height: 137.0,
                              child: GeneratedCafelatteWidget(),
                            ),
                            Positioned(
                              left: 5.0,
                              top: 562.0,
                              right: null,
                              bottom: null,
                              width: 395.0,
                              height: 137.0,
                              child: GeneratedCafemochaWidget(),
                            ),
                            Positioned(
                              left: 10.0,
                              top: 183.0,
                              right: null,
                              bottom: null,
                              width: 393.0,
                              height: 136.0,
                              child: GeneratedAMERICANOWidget(),
                            ),
                            Positioned(
                              left: 3.0,
                              top: 699.0,
                              right: null,
                              bottom: null,
                              width: 395.0,
                              height: 135.0,
                              child: GeneratedESPRESSOWidget(),
                            ),
                            Positioned(
                              left: 187.0,
                              top: 151.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 27.0,
                              child: Generated12Widget(),
                            ),
                            Positioned(
                              left: 267.0,
                              top: 865.0,
                              right: null,
                              bottom: null,
                              width: 95.0,
                              height: 1.0,
                              child: GeneratedLine15Widget(),
                            ),
                            Positioned(
                              left: 5.0,
                              top: 307.0,
                              right: null,
                              bottom: null,
                              width: 383.9999084472656,
                              height: 144.0,
                              child: GeneratedPIZZAWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -79.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 223.0,
                              child: GeneratedGroup1Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: -4.0,
                              right: null,
                              bottom: null,
                              width: 0.0,
                              height: 0.0,
                              child: GeneratedWhitesymbolsWidget(),
                            ),
                            Positioned(
                              left: -6.0,
                              top: 20.0,
                              right: null,
                              bottom: null,
                              width: 421.0,
                              height: 1.0,
                              child: GeneratedLine5Widget(),
                            ),
                            Positioned(
                              left: -5.0,
                              top: 10.0,
                              right: null,
                              bottom: null,
                              width: 424.0,
                              height: 1.0,
                              child: GeneratedLine6Widget(),
                            ),
                            Positioned(
                              left: 10.0,
                              top: 29.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 12.0,
                              child: GeneratedBackWidget1(),
                            ),
                            Positioned(
                              left: 315.0,
                              top: 29.0,
                              right: null,
                              bottom: null,
                              width: 102.0,
                              height: 22.0,
                              child: GeneratedViewOrderSummaryWidget(),
                            ),
                            Positioned(
                              left: 169.0,
                              top: 106.0,
                              right: null,
                              bottom: null,
                              width: 81.0,
                              height: 32.0,
                              child: GeneratedMenuWidget(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: -48.0,
                              right: null,
                              bottom: null,
                              width: 274.0,
                              height: 274.0,
                              child: GeneratedCoffeemainlogoWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
