import 'package:flutter/material.dart';
import 'package:flutterapp/comeonapp/generatedwaffleswidget/generated/GeneratedBackWidget10.dart';
import 'package:flutterapp/comeonapp/generatedwaffleswidget/generated/GeneratedCoffeebackgroundWidget6.dart';
import 'package:flutterapp/comeonapp/generatedwaffleswidget/generated/GeneratedWhitesymbolsWidget5.dart';
import 'package:flutterapp/comeonapp/generatedwaffleswidget/generated/GeneratedExtracrisphappybakedbigtexturedsunsetsplendidlypuffyand.dart';
import 'package:flutterapp/comeonapp/generatedwaffleswidget/generated/GeneratedPriceWidget4.dart';
import 'package:flutterapp/comeonapp/generatedwaffleswidget/generated/GeneratedLine8Widget3.dart';
import 'package:flutterapp/comeonapp/generatedwaffleswidget/generated/GeneratedBrownrectangleWidget5.dart';
import 'package:flutterapp/comeonapp/generatedwaffleswidget/generated/GeneratedWafflesWidget1.dart';
import 'package:flutterapp/comeonapp/generatedwaffleswidget/generated/GeneratedAddToBuyWidget4.dart';
import 'package:flutterapp/comeonapp/generatedwaffleswidget/generated/GeneratedBackWidget11.dart';
import 'package:flutterapp/comeonapp/generatedwaffleswidget/generated/GeneratedRectangle2Widget4.dart';
import 'package:flutterapp/comeonapp/generatedwaffleswidget/generated/GeneratedWhiterectangletopWidget4.dart';
import 'package:flutterapp/comeonapp/generatedwaffleswidget/generated/GeneratedWaffles1Widget.dart';
import 'package:flutterapp/comeonapp/generatedwaffleswidget/generated/GeneratedCoffeemainlogoWidget6.dart';
import 'package:flutterapp/comeonapp/generatedwaffleswidget/generated/Generated129Widget3.dart';
import 'package:flutterapp/comeonapp/generatedwaffleswidget/generated/GeneratedRectangle1Widget4.dart';
import 'package:flutterapp/comeonapp/generatedwaffleswidget/generated/GeneratedLine7Widget3.dart';

/* Frame waffles
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWafflesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1360.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 896.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -270.0,
                              top: 162.0,
                              right: null,
                              bottom: null,
                              width: 1080.0,
                              height: 887.0,
                              child: GeneratedCoffeebackgroundWidget6(),
                            ),
                            Positioned(
                              left: -260.0,
                              top: 1348.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 12.0,
                              child: GeneratedBackWidget10(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 730.0,
                              right: null,
                              bottom: null,
                              width: 256.0,
                              height: 37.0,
                              child: GeneratedRectangle1Widget4(),
                            ),
                            Positioned(
                              left: 131.0,
                              top: 740.0,
                              right: null,
                              bottom: null,
                              width: 154.0,
                              height: 18.0,
                              child: GeneratedAddToBuyWidget4(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -165.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 309.0,
                              child: GeneratedBrownrectangleWidget5(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: -5.0,
                              right: null,
                              bottom: null,
                              width: 0.0,
                              height: 0.0,
                              child: GeneratedWhitesymbolsWidget5(),
                            ),
                            Positioned(
                              left: -6.0,
                              top: 19.0,
                              right: null,
                              bottom: null,
                              width: 421.0,
                              height: 1.0,
                              child: GeneratedLine7Widget3(),
                            ),
                            Positioned(
                              left: -5.0,
                              top: 9.0,
                              right: null,
                              bottom: null,
                              width: 424.0,
                              height: 1.0,
                              child: GeneratedLine8Widget3(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 111.0,
                              right: null,
                              bottom: null,
                              width: 325.0,
                              height: 598.0,
                              child: GeneratedWhiterectangletopWidget4(),
                            ),
                            Positioned(
                              left: 166.0,
                              top: 592.0,
                              right: null,
                              bottom: null,
                              width: 111.0,
                              height: 57.0,
                              child: Generated129Widget3(),
                            ),
                            Positioned(
                              left: 131.0,
                              top: 577.0,
                              right: null,
                              bottom: null,
                              width: 152.0,
                              height: 71.0,
                              child: GeneratedRectangle2Widget4(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 584.0,
                              right: null,
                              bottom: null,
                              width: 51.0,
                              height: 18.0,
                              child: GeneratedPriceWidget4(),
                            ),
                            Positioned(
                              left: 58.0,
                              top: 477.0,
                              right: null,
                              bottom: null,
                              width: 306.0,
                              height: 47.0,
                              child:
                                  GeneratedExtracrisphappybakedbigtexturedsunsetsplendidlypuffyand(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 144.0,
                              right: null,
                              bottom: null,
                              width: 256.0,
                              height: 251.0,
                              child: GeneratedWaffles1Widget(),
                            ),
                            Positioned(
                              left: 141.0,
                              top: 410.0,
                              right: null,
                              bottom: null,
                              width: 137.0,
                              height: 26.0,
                              child: GeneratedWafflesWidget1(),
                            ),
                            Positioned(
                              left: 10.0,
                              top: 29.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 12.0,
                              child: GeneratedBackWidget11(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: -48.0,
                              right: null,
                              bottom: null,
                              width: 274.0,
                              height: 274.0,
                              child: GeneratedCoffeemainlogoWidget6(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
