import 'package:flutter/material.dart';
import 'package:flutterapp/comeonapp/generatedclubsandwichwidget/generated/GeneratedLayersofhambaconandturkeywithjuicytomatoescrisplettucea.dart';
import 'package:flutterapp/comeonapp/generatedclubsandwichwidget/generated/GeneratedLine8Widget1.dart';
import 'package:flutterapp/comeonapp/generatedclubsandwichwidget/generated/GeneratedBackWidget6.dart';
import 'package:flutterapp/comeonapp/generatedclubsandwichwidget/generated/GeneratedBackWidget7.dart';
import 'package:flutterapp/comeonapp/generatedclubsandwichwidget/generated/GeneratedWhiterectangletopWidget2.dart';
import 'package:flutterapp/comeonapp/generatedclubsandwichwidget/generated/GeneratedRectangle2Widget2.dart';
import 'package:flutterapp/comeonapp/generatedclubsandwichwidget/generated/GeneratedWhitesymbolsWidget3.dart';
import 'package:flutterapp/comeonapp/generatedclubsandwichwidget/generated/GeneratedCoffeemainlogoWidget4.dart';
import 'package:flutterapp/comeonapp/generatedclubsandwichwidget/generated/GeneratedClubSandwichWidget.dart';
import 'package:flutterapp/comeonapp/generatedclubsandwichwidget/generated/GeneratedPriceWidget2.dart';
import 'package:flutterapp/comeonapp/generatedclubsandwichwidget/generated/Generated129Widget1.dart';
import 'package:flutterapp/comeonapp/generatedclubsandwichwidget/generated/GeneratedAddToBuyWidget2.dart';
import 'package:flutterapp/comeonapp/generatedclubsandwichwidget/generated/GeneratedCoffeebackgroundWidget4.dart';
import 'package:flutterapp/comeonapp/generatedclubsandwichwidget/generated/GeneratedRectangle1Widget2.dart';
import 'package:flutterapp/comeonapp/generatedclubsandwichwidget/generated/GeneratedLine7Widget1.dart';
import 'package:flutterapp/comeonapp/generatedclubsandwichwidget/generated/GeneratedClubsandwich1Widget.dart';
import 'package:flutterapp/comeonapp/generatedclubsandwichwidget/generated/GeneratedBrownrectangleWidget3.dart';

/* Frame club sandwich
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedClubsandwichWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1360.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 896.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -260.0,
                              top: 1348.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 12.0,
                              child: GeneratedBackWidget6(),
                            ),
                            Positioned(
                              left: -352.0,
                              top: 64.0,
                              right: null,
                              bottom: null,
                              width: 1109.0,
                              height: 882.0,
                              child: GeneratedCoffeebackgroundWidget4(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 730.0,
                              right: null,
                              bottom: null,
                              width: 256.0,
                              height: 37.0,
                              child: GeneratedRectangle1Widget2(),
                            ),
                            Positioned(
                              left: 131.0,
                              top: 740.0,
                              right: null,
                              bottom: null,
                              width: 154.0,
                              height: 18.0,
                              child: GeneratedAddToBuyWidget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -165.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 309.0,
                              child: GeneratedBrownrectangleWidget3(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: -5.0,
                              right: null,
                              bottom: null,
                              width: 0.0,
                              height: 0.0,
                              child: GeneratedWhitesymbolsWidget3(),
                            ),
                            Positioned(
                              left: -6.0,
                              top: 19.0,
                              right: null,
                              bottom: null,
                              width: 421.0,
                              height: 1.0,
                              child: GeneratedLine7Widget1(),
                            ),
                            Positioned(
                              left: -5.0,
                              top: 9.0,
                              right: null,
                              bottom: null,
                              width: 424.0,
                              height: 1.0,
                              child: GeneratedLine8Widget1(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 111.0,
                              right: null,
                              bottom: null,
                              width: 325.0,
                              height: 598.0,
                              child: GeneratedWhiterectangletopWidget2(),
                            ),
                            Positioned(
                              left: 166.0,
                              top: 592.0,
                              right: null,
                              bottom: null,
                              width: 111.0,
                              height: 57.0,
                              child: Generated129Widget1(),
                            ),
                            Positioned(
                              left: 131.0,
                              top: 577.0,
                              right: null,
                              bottom: null,
                              width: 152.0,
                              height: 71.0,
                              child: GeneratedRectangle2Widget2(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 584.0,
                              right: null,
                              bottom: null,
                              width: 51.0,
                              height: 18.0,
                              child: GeneratedPriceWidget2(),
                            ),
                            Positioned(
                              left: 28.0,
                              top: 477.0,
                              right: null,
                              bottom: null,
                              width: 367.0,
                              height: 62.0,
                              child:
                                  GeneratedLayersofhambaconandturkeywithjuicytomatoescrisplettucea(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 144.0,
                              right: null,
                              bottom: null,
                              width: 256.0,
                              height: 251.0,
                              child: GeneratedClubsandwich1Widget(),
                            ),
                            Positioned(
                              left: 80.0,
                              top: 410.0,
                              right: null,
                              bottom: null,
                              width: 255.0,
                              height: 23.0,
                              child: GeneratedClubSandwichWidget(),
                            ),
                            Positioned(
                              left: 10.0,
                              top: 29.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 12.0,
                              child: GeneratedBackWidget7(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: -48.0,
                              right: null,
                              bottom: null,
                              width: 274.0,
                              height: 274.0,
                              child: GeneratedCoffeemainlogoWidget4(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
