import 'package:flutter/material.dart';
import 'package:flutterapp/comeonapp/generatedcroissantwidget/generated/GeneratedPriceWidget3.dart';
import 'package:flutterapp/comeonapp/generatedcroissantwidget/generated/GeneratedAddToBuyWidget3.dart';
import 'package:flutterapp/comeonapp/generatedcroissantwidget/generated/GeneratedCoffeemainlogoWidget5.dart';
import 'package:flutterapp/comeonapp/generatedcroissantwidget/generated/GeneratedWhitesymbolsWidget4.dart';
import 'package:flutterapp/comeonapp/generatedcroissantwidget/generated/GeneratedLine8Widget2.dart';
import 'package:flutterapp/comeonapp/generatedcroissantwidget/generated/GeneratedCoffeebackgroundWidget5.dart';
import 'package:flutterapp/comeonapp/generatedcroissantwidget/generated/GeneratedClubsandwich1Widget1.dart';
import 'package:flutterapp/comeonapp/generatedcroissantwidget/generated/GeneratedBackWidget9.dart';
import 'package:flutterapp/comeonapp/generatedcroissantwidget/generated/GeneratedBrownrectangleWidget4.dart';
import 'package:flutterapp/comeonapp/generatedcroissantwidget/generated/GeneratedThisclassiccroissantismadewithrealbuttertocreateagolden.dart';
import 'package:flutterapp/comeonapp/generatedcroissantwidget/generated/GeneratedCriossant1Widget.dart';
import 'package:flutterapp/comeonapp/generatedcroissantwidget/generated/GeneratedRectangle1Widget3.dart';
import 'package:flutterapp/comeonapp/generatedcroissantwidget/generated/GeneratedBackWidget8.dart';
import 'package:flutterapp/comeonapp/generatedcroissantwidget/generated/GeneratedRectangle2Widget3.dart';
import 'package:flutterapp/comeonapp/generatedcroissantwidget/generated/GeneratedWhiterectangletopWidget3.dart';
import 'package:flutterapp/comeonapp/generatedcroissantwidget/generated/Generated129Widget2.dart';
import 'package:flutterapp/comeonapp/generatedcroissantwidget/generated/GeneratedLine7Widget2.dart';
import 'package:flutterapp/comeonapp/generatedcroissantwidget/generated/GeneratedCroissantWidget1.dart';

/* Frame croissant
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCroissantWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1360.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 896.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -270.0,
                              top: 162.0,
                              right: null,
                              bottom: null,
                              width: 1080.0,
                              height: 887.0,
                              child: GeneratedCoffeebackgroundWidget5(),
                            ),
                            Positioned(
                              left: -260.0,
                              top: 1348.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 12.0,
                              child: GeneratedBackWidget8(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 730.0,
                              right: null,
                              bottom: null,
                              width: 256.0,
                              height: 37.0,
                              child: GeneratedRectangle1Widget3(),
                            ),
                            Positioned(
                              left: 131.0,
                              top: 740.0,
                              right: null,
                              bottom: null,
                              width: 154.0,
                              height: 18.0,
                              child: GeneratedAddToBuyWidget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -165.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 309.0,
                              child: GeneratedBrownrectangleWidget4(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: -5.0,
                              right: null,
                              bottom: null,
                              width: 0.0,
                              height: 0.0,
                              child: GeneratedWhitesymbolsWidget4(),
                            ),
                            Positioned(
                              left: -6.0,
                              top: 19.0,
                              right: null,
                              bottom: null,
                              width: 421.0,
                              height: 1.0,
                              child: GeneratedLine7Widget2(),
                            ),
                            Positioned(
                              left: -5.0,
                              top: 9.0,
                              right: null,
                              bottom: null,
                              width: 424.0,
                              height: 1.0,
                              child: GeneratedLine8Widget2(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 111.0,
                              right: null,
                              bottom: null,
                              width: 325.0,
                              height: 598.0,
                              child: GeneratedWhiterectangletopWidget3(),
                            ),
                            Positioned(
                              left: 158.0,
                              top: 592.0,
                              right: null,
                              bottom: null,
                              width: 111.0,
                              height: 57.0,
                              child: Generated129Widget2(),
                            ),
                            Positioned(
                              left: 131.0,
                              top: 577.0,
                              right: null,
                              bottom: null,
                              width: 152.0,
                              height: 71.0,
                              child: GeneratedRectangle2Widget3(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 584.0,
                              right: null,
                              bottom: null,
                              width: 51.0,
                              height: 18.0,
                              child: GeneratedPriceWidget3(),
                            ),
                            Positioned(
                              left: 33.0,
                              top: 477.0,
                              right: null,
                              bottom: null,
                              width: 357.0,
                              height: 62.0,
                              child:
                                  GeneratedThisclassiccroissantismadewithrealbuttertocreateagolden(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 144.0,
                              right: null,
                              bottom: null,
                              width: 256.0,
                              height: 251.0,
                              child: GeneratedClubsandwich1Widget1(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 144.0,
                              right: null,
                              bottom: null,
                              width: 256.0,
                              height: 251.0,
                              child: GeneratedCriossant1Widget(),
                            ),
                            Positioned(
                              left: 125.0,
                              top: 410.0,
                              right: null,
                              bottom: null,
                              width: 177.0,
                              height: 26.0,
                              child: GeneratedCroissantWidget1(),
                            ),
                            Positioned(
                              left: 10.0,
                              top: 29.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 12.0,
                              child: GeneratedBackWidget9(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: -48.0,
                              right: null,
                              bottom: null,
                              width: 274.0,
                              height: 274.0,
                              child: GeneratedCoffeemainlogoWidget5(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
