import 'package:flutter/material.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/Generated320Widget.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/GeneratedLine10Widget.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/GeneratedOrderSummaryWidget.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/GeneratedVector1Widget.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/GeneratedWhiterectanglebottomWidget.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/Generated30Widget.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/GeneratedCheckoutWidget.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/GeneratedDeliveryWidget.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/GeneratedAmericano3Widget1.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/Generated50Widget.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/GeneratedBlackcoffee2Widget.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/GeneratedGreenrectangleWidget1.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/GeneratedBlackCoffeeWidget.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/GeneratedLine9Widget.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/GeneratedCoffeebackgroundWidget11.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/GeneratedTaxFeesWidget.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/GeneratedSubtotalWidget.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/GeneratedTotalWidget.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/GeneratedBackWidget20.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/GeneratedAmericanoWidget2.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/GeneratedBlackcoffeesquareboxesWidget.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/Generated400Widget.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/GeneratedCoffeemainlogoWidget11.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/GeneratedWhitesymbolsWidget10.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/GeneratedAmericanosquareboxesWidget.dart';
import 'package:flutterapp/comeonapp/generatedordersummarywidget/generated/GeneratedWhiterectangletopWidget9.dart';

/* Frame order summary
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOrdersummaryWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1049.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 896.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -270.0,
                              top: 162.0,
                              right: null,
                              bottom: null,
                              width: 1080.0,
                              height: 887.0,
                              child: GeneratedCoffeebackgroundWidget11(),
                            ),
                            Positioned(
                              left: 73.0,
                              top: 731.0,
                              right: null,
                              bottom: null,
                              width: 256.0,
                              height: 37.0,
                              child: GeneratedRectangle3Widget(),
                            ),
                            Positioned(
                              left: 145.0,
                              top: 740.0,
                              right: null,
                              bottom: null,
                              width: 136.0,
                              height: 29.0,
                              child: GeneratedCheckoutWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -165.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 370.0,
                              child: GeneratedGreenrectangleWidget1(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: -5.0,
                              right: null,
                              bottom: null,
                              width: 0.0,
                              height: 0.0,
                              child: GeneratedWhitesymbolsWidget10(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 19.0,
                              right: null,
                              bottom: null,
                              width: 421.0,
                              height: 1.0,
                              child: GeneratedLine9Widget(),
                            ),
                            Positioned(
                              left: 1.0,
                              top: 9.0,
                              right: null,
                              bottom: null,
                              width: 424.0,
                              height: 1.0,
                              child: GeneratedLine10Widget(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 162.0,
                              right: null,
                              bottom: null,
                              width: 325.0,
                              height: 203.0,
                              child: GeneratedWhiterectangletopWidget9(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 386.0,
                              right: null,
                              bottom: null,
                              width: 325.0,
                              height: 323.0,
                              child: GeneratedWhiterectanglebottomWidget(),
                            ),
                            Positioned(
                              left: 228.0,
                              top: 431.0,
                              right: null,
                              bottom: null,
                              width: 101.0,
                              height: 56.0,
                              child: GeneratedAmericanosquareboxesWidget(),
                            ),
                            Positioned(
                              left: 223.0,
                              top: 563.0,
                              right: null,
                              bottom: null,
                              width: 106.0,
                              height: 56.0,
                              child: GeneratedBlackcoffeesquareboxesWidget(),
                            ),
                            Positioned(
                              left: 80.0,
                              top: 539.0,
                              right: null,
                              bottom: null,
                              width: 90.0,
                              height: 88.0,
                              child: GeneratedBlackcoffee2Widget(),
                            ),
                            Positioned(
                              left: 195.0,
                              top: 553.0,
                              right: null,
                              bottom: null,
                              width: 177.0,
                              height: 18.0,
                              child: GeneratedBlackCoffeeWidget(),
                            ),
                            Positioned(
                              left: 170.0,
                              top: 411.0,
                              right: null,
                              bottom: null,
                              width: 90.0,
                              height: 88.0,
                              child: GeneratedAmericano3Widget1(),
                            ),
                            Positioned(
                              left: 216.0,
                              top: 419.0,
                              right: null,
                              bottom: null,
                              width: 185.0,
                              height: 34.0,
                              child: GeneratedAmericanoWidget2(),
                            ),
                            Positioned(
                              left: 65.0,
                              top: 287.0,
                              right: null,
                              bottom: null,
                              width: 279.0018005371094,
                              height: 0.0,
                              child: GeneratedVector1Widget(),
                            ),
                            Positioned(
                              left: 65.0,
                              top: 187.0,
                              right: null,
                              bottom: null,
                              width: 263.0,
                              height: 23.0,
                              child: GeneratedSubtotalWidget(),
                            ),
                            Positioned(
                              left: 305.0,
                              top: 184.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 22.0,
                              child: Generated320Widget(),
                            ),
                            Positioned(
                              left: 304.0,
                              top: 217.0,
                              right: null,
                              bottom: null,
                              width: 42.0,
                              height: 19.0,
                              child: Generated50Widget(),
                            ),
                            Positioned(
                              left: 304.0,
                              top: 247.0,
                              right: null,
                              bottom: null,
                              width: 42.0,
                              height: 19.0,
                              child: Generated30Widget(),
                            ),
                            Positioned(
                              left: 65.0,
                              top: 217.0,
                              right: null,
                              bottom: null,
                              width: 260.0,
                              height: 20.0,
                              child: GeneratedTaxFeesWidget(),
                            ),
                            Positioned(
                              left: 65.0,
                              top: 247.0,
                              right: null,
                              bottom: null,
                              width: 263.0,
                              height: 23.0,
                              child: GeneratedDeliveryWidget(),
                            ),
                            Positioned(
                              left: 65.0,
                              top: 301.0,
                              right: null,
                              bottom: null,
                              width: 263.0,
                              height: 23.0,
                              child: GeneratedTotalWidget(),
                            ),
                            Positioned(
                              left: 290.0,
                              top: 299.0,
                              right: null,
                              bottom: null,
                              width: 263.0,
                              height: 23.0,
                              child: Generated400Widget(),
                            ),
                            Positioned(
                              left: 103.0,
                              top: 99.0,
                              right: null,
                              bottom: null,
                              width: 222.0,
                              height: 40.0,
                              child: GeneratedOrderSummaryWidget(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: -48.0,
                              right: null,
                              bottom: null,
                              width: 274.0,
                              height: 274.0,
                              child: GeneratedCoffeemainlogoWidget11(),
                            ),
                            Positioned(
                              left: 7.0,
                              top: 30.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 12.0,
                              child: GeneratedBackWidget20(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
