import 'package:flutter/material.dart';
import 'package:flutterapp/comeonapp/generatedthirdpagewidget/generated/GeneratedBackWidget21.dart';
import 'package:flutterapp/comeonapp/generatedthirdpagewidget/generated/Generated22Widget.dart';
import 'package:flutterapp/comeonapp/generatedthirdpagewidget/generated/GeneratedViewOrderSummaryWidget1.dart';
import 'package:flutterapp/comeonapp/generatedthirdpagewidget/generated/GeneratedWAFFLESWidget.dart';
import 'package:flutterapp/comeonapp/generatedthirdpagewidget/generated/GeneratedCROISSANTWidget.dart';
import 'package:flutterapp/comeonapp/generatedthirdpagewidget/generated/GeneratedCoffeebackgroundWidget13.dart';
import 'package:flutterapp/comeonapp/generatedthirdpagewidget/generated/GeneratedORGANICCOFFEEWidget.dart';
import 'package:flutterapp/comeonapp/generatedthirdpagewidget/generated/GeneratedCoffeemainlogoWidget12.dart';
import 'package:flutterapp/comeonapp/generatedthirdpagewidget/generated/GeneratedGroup1Widget1.dart';
import 'package:flutterapp/comeonapp/generatedthirdpagewidget/generated/GeneratedClubsandwichWidget1.dart';
import 'package:flutterapp/comeonapp/generatedthirdpagewidget/generated/GeneratedMenuWidget1.dart';

/* Frame third page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedThirdpageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -352.0,
                top: 106.0,
                right: null,
                bottom: null,
                width: 1080.0,
                height: 790.0,
                child: GeneratedCoffeebackgroundWidget13(),
              ),
              Positioned(
                left: 188.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 33.0,
                child: Generated22Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 191.0,
                right: null,
                bottom: null,
                width: 394.99993896484375,
                height: 137.0,
                child: GeneratedORGANICCOFFEEWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 120.0,
                child: GeneratedClubsandwichWidget1(),
              ),
              Positioned(
                left: 14.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 385.0,
                height: 142.0,
                child: GeneratedCROISSANTWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 129.0,
                child: GeneratedWAFFLESWidget(),
              ),
              Positioned(
                left: 0.0,
                top: -79.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 223.0,
                child: GeneratedGroup1Widget1(),
              ),
              Positioned(
                left: 10.0,
                top: 29.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 12.0,
                child: GeneratedBackWidget21(),
              ),
              Positioned(
                left: 70.0,
                top: -48.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 274.0,
                child: GeneratedCoffeemainlogoWidget12(),
              ),
              Positioned(
                left: 305.0,
                top: 29.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 22.0,
                child: GeneratedViewOrderSummaryWidget1(),
              ),
              Positioned(
                left: 169.0,
                top: 106.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 32.0,
                child: GeneratedMenuWidget1(),
              )
            ]),
      ),
    ));
  }
}
