import 'package:flutter/material.dart';
import 'package:flutterapp/comeonapp/generatedcafelattewidget2/generated/GeneratedWhatsAppImage20210829at14251Widget.dart';
import 'package:flutterapp/comeonapp/generatedcafelattewidget2/generated/Generated89Widget1.dart';
import 'package:flutterapp/comeonapp/generatedcafelattewidget2/generated/GeneratedCoffeebackgroundWidget3.dart';
import 'package:flutterapp/comeonapp/generatedcafelattewidget2/generated/GeneratedCoffeemainlogoWidget3.dart';
import 'package:flutterapp/comeonapp/generatedcafelattewidget2/generated/GeneratedBrownrectangleWidget2.dart';
import 'package:flutterapp/comeonapp/generatedcafelattewidget2/generated/GeneratedAddToBuyWidget1.dart';
import 'package:flutterapp/comeonapp/generatedcafelattewidget2/generated/GeneratedBackWidget5.dart';
import 'package:flutterapp/comeonapp/generatedcafelattewidget2/generated/GeneratedWhitesymbolsWidget2.dart';
import 'package:flutterapp/comeonapp/generatedcafelattewidget2/generated/GeneratedLine8Widget.dart';
import 'package:flutterapp/comeonapp/generatedcafelattewidget2/generated/GeneratedLine7Widget.dart';
import 'package:flutterapp/comeonapp/generatedcafelattewidget2/generated/GeneratedRectangle2Widget1.dart';
import 'package:flutterapp/comeonapp/generatedcafelattewidget2/generated/GeneratedCaffLatteWidget.dart';
import 'package:flutterapp/comeonapp/generatedcafelattewidget2/generated/GeneratedOurdarkrichespressobalancedwithsteamedmilkandlightlayer.dart';
import 'package:flutterapp/comeonapp/generatedcafelattewidget2/generated/GeneratedBackWidget4.dart';
import 'package:flutterapp/comeonapp/generatedcafelattewidget2/generated/GeneratedPriceWidget1.dart';
import 'package:flutterapp/comeonapp/generatedcafelattewidget2/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/comeonapp/generatedcafelattewidget2/generated/GeneratedWhiterectangletopWidget1.dart';

/* Frame cafe latte
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCafelatteWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1360.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 896.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -270.0,
                              top: 162.0,
                              right: null,
                              bottom: null,
                              width: 1080.0,
                              height: 887.0,
                              child: GeneratedCoffeebackgroundWidget3(),
                            ),
                            Positioned(
                              left: -260.0,
                              top: 1348.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 12.0,
                              child: GeneratedBackWidget4(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 730.0,
                              right: null,
                              bottom: null,
                              width: 256.0,
                              height: 37.0,
                              child: GeneratedRectangle1Widget1(),
                            ),
                            Positioned(
                              left: 131.0,
                              top: 740.0,
                              right: null,
                              bottom: null,
                              width: 154.0,
                              height: 18.0,
                              child: GeneratedAddToBuyWidget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -165.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 309.0,
                              child: GeneratedBrownrectangleWidget2(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: -5.0,
                              right: null,
                              bottom: null,
                              width: 0.0,
                              height: 0.0,
                              child: GeneratedWhitesymbolsWidget2(),
                            ),
                            Positioned(
                              left: -6.0,
                              top: 19.0,
                              right: null,
                              bottom: null,
                              width: 421.0,
                              height: 1.0,
                              child: GeneratedLine7Widget(),
                            ),
                            Positioned(
                              left: -5.0,
                              top: 9.0,
                              right: null,
                              bottom: null,
                              width: 424.0,
                              height: 1.0,
                              child: GeneratedLine8Widget(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 111.0,
                              right: null,
                              bottom: null,
                              width: 325.0,
                              height: 598.0,
                              child: GeneratedWhiterectangletopWidget1(),
                            ),
                            Positioned(
                              left: 166.0,
                              top: 592.0,
                              right: null,
                              bottom: null,
                              width: 84.0,
                              height: 57.0,
                              child: Generated89Widget1(),
                            ),
                            Positioned(
                              left: 131.0,
                              top: 577.0,
                              right: null,
                              bottom: null,
                              width: 152.0,
                              height: 71.0,
                              child: GeneratedRectangle2Widget1(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 584.0,
                              right: null,
                              bottom: null,
                              width: 51.0,
                              height: 18.0,
                              child: GeneratedPriceWidget1(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 477.0,
                              right: null,
                              bottom: null,
                              width: 347.0,
                              height: 62.0,
                              child:
                                  GeneratedOurdarkrichespressobalancedwithsteamedmilkandlightlayer(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 145.0,
                              right: null,
                              bottom: null,
                              width: 256.0,
                              height: 250.0,
                              child:
                                  GeneratedWhatsAppImage20210829at14251Widget(),
                            ),
                            Positioned(
                              left: 105.0,
                              top: 410.0,
                              right: null,
                              bottom: null,
                              width: 214.0,
                              height: 23.0,
                              child: GeneratedCaffLatteWidget(),
                            ),
                            Positioned(
                              left: 10.0,
                              top: 29.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 12.0,
                              child: GeneratedBackWidget5(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: -48.0,
                              right: null,
                              bottom: null,
                              width: 274.0,
                              height: 274.0,
                              child: GeneratedCoffeemainlogoWidget3(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
