import 'package:flutter/material.dart';
import 'package:flutterapp/comeonapp/generatedstartingpagewidget/generated/GeneratedLatteWidget1.dart';
import 'package:flutterapp/comeonapp/generatedstartingpagewidget/generated/GeneratedCoffeeshoplogo21Widget.dart';
import 'package:flutterapp/comeonapp/generatedstartingpagewidget/generated/GeneratedGreenrectangleWidget.dart';
import 'package:flutterapp/comeonapp/generatedstartingpagewidget/generated/GeneratedCoffeemainlogoWidget.dart';
import 'package:flutterapp/comeonapp/generatedstartingpagewidget/generated/GeneratedCoffee_logo1Widget.dart';
import 'package:flutterapp/comeonapp/generatedstartingpagewidget/generated/GeneratedBlacksymbilsWidget.dart';
import 'package:flutterapp/comeonapp/generatedstartingpagewidget/generated/GeneratedCoffeebackgroundWidget.dart';
import 'package:flutterapp/comeonapp/generatedstartingpagewidget/generated/GeneratedLatteWidget.dart';
import 'package:flutterapp/comeonapp/generatedstartingpagewidget/generated/GeneratedSINCE1989Widget.dart';
import 'package:flutterapp/comeonapp/generatedstartingpagewidget/generated/GeneratedCoffeeshoplogo1Widget.dart';

/* Frame Starting Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedStartingPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -147.0,
                top: -116.0,
                right: null,
                bottom: null,
                width: 1080.0,
                height: 1080.0,
                child: GeneratedCoffeebackgroundWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 526.0,
                child: GeneratedGreenrectangleWidget(),
              ),
              Positioned(
                left: 148.0,
                top: 750.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 130.0,
                child: GeneratedCoffee_logo1Widget(),
              ),
              Positioned(
                left: -102.0,
                top: 285.0,
                right: null,
                bottom: null,
                width: 619.0,
                height: 619.0,
                child: GeneratedCoffeemainlogoWidget(),
              ),
              Positioned(
                left: 110.0,
                top: 787.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 19.0,
                child: GeneratedSINCE1989Widget(),
              ),
              Positioned(
                left: 123.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 89.0,
                child: GeneratedLatteWidget(),
              ),
              Positioned(
                left: 91.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 110.0,
                child: GeneratedLatteWidget1(),
              ),
              Positioned(
                left: -685.0,
                top: 127.0,
                right: null,
                bottom: null,
                width: 1080.0,
                height: 1080.0,
                child: GeneratedCoffeeshoplogo1Widget(),
              ),
              Positioned(
                left: -351.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 1080.0,
                height: 1080.0,
                child: GeneratedCoffeeshoplogo21Widget(),
              ),
              Positioned(
                left: 28.0,
                top: -4.0,
                right: null,
                bottom: null,
                width: 0.0,
                height: 0.0,
                child: GeneratedBlacksymbilsWidget(),
              )
            ]),
      ),
    ));
  }
}
