import 'package:flutter/material.dart';
import 'package:flutterapp/comeonapp/generatedespressowidget/generated/GeneratedWhitesymbolsWidget8.dart';
import 'package:flutterapp/comeonapp/generatedespressowidget/generated/GeneratedLine7Widget6.dart';
import 'package:flutterapp/comeonapp/generatedespressowidget/generated/GeneratedRectangle2Widget7.dart';
import 'package:flutterapp/comeonapp/generatedespressowidget/generated/GeneratedCoffeemainlogoWidget9.dart';
import 'package:flutterapp/comeonapp/generatedespressowidget/generated/GeneratedRectangle1Widget7.dart';
import 'package:flutterapp/comeonapp/generatedespressowidget/generated/GeneratedAddToBuyWidget7.dart';
import 'package:flutterapp/comeonapp/generatedespressowidget/generated/GeneratedBackWidget17.dart';
import 'package:flutterapp/comeonapp/generatedespressowidget/generated/GeneratedWhiterectangletopWidget7.dart';
import 'package:flutterapp/comeonapp/generatedespressowidget/generated/GeneratedPriceWidget7.dart';
import 'package:flutterapp/comeonapp/generatedespressowidget/generated/Generated99Widget1.dart';
import 'package:flutterapp/comeonapp/generatedespressowidget/generated/GeneratedCoffeebackgroundWidget9.dart';
import 'package:flutterapp/comeonapp/generatedespressowidget/generated/GeneratedEspressoWidget1.dart';
import 'package:flutterapp/comeonapp/generatedespressowidget/generated/GeneratedEspressoWidget2.dart';
import 'package:flutterapp/comeonapp/generatedespressowidget/generated/GeneratedBackWidget16.dart';
import 'package:flutterapp/comeonapp/generatedespressowidget/generated/GeneratedBrownrectangleWidget8.dart';
import 'package:flutterapp/comeonapp/generatedespressowidget/generated/GeneratedOurrichfullbodiedespressocombinedwithbittersweetmochasa1.dart';
import 'package:flutterapp/comeonapp/generatedespressowidget/generated/GeneratedLine8Widget6.dart';

/* Frame espresso
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEspressoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1360.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 896.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -270.0,
                              top: 162.0,
                              right: null,
                              bottom: null,
                              width: 1080.0,
                              height: 887.0,
                              child: GeneratedCoffeebackgroundWidget9(),
                            ),
                            Positioned(
                              left: -260.0,
                              top: 1348.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 12.0,
                              child: GeneratedBackWidget16(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 730.0,
                              right: null,
                              bottom: null,
                              width: 256.0,
                              height: 37.0,
                              child: GeneratedRectangle1Widget7(),
                            ),
                            Positioned(
                              left: 131.0,
                              top: 740.0,
                              right: null,
                              bottom: null,
                              width: 154.0,
                              height: 18.0,
                              child: GeneratedAddToBuyWidget7(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -165.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 309.0,
                              child: GeneratedBrownrectangleWidget8(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: -5.0,
                              right: null,
                              bottom: null,
                              width: 0.0,
                              height: 0.0,
                              child: GeneratedWhitesymbolsWidget8(),
                            ),
                            Positioned(
                              left: -6.0,
                              top: 19.0,
                              right: null,
                              bottom: null,
                              width: 421.0,
                              height: 1.0,
                              child: GeneratedLine7Widget6(),
                            ),
                            Positioned(
                              left: -5.0,
                              top: 9.0,
                              right: null,
                              bottom: null,
                              width: 424.0,
                              height: 1.0,
                              child: GeneratedLine8Widget6(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 111.0,
                              right: null,
                              bottom: null,
                              width: 325.0,
                              height: 598.0,
                              child: GeneratedWhiterectangletopWidget7(),
                            ),
                            Positioned(
                              left: 170.0,
                              top: 592.0,
                              right: null,
                              bottom: null,
                              width: 84.0,
                              height: 57.0,
                              child: Generated99Widget1(),
                            ),
                            Positioned(
                              left: 131.0,
                              top: 577.0,
                              right: null,
                              bottom: null,
                              width: 152.0,
                              height: 71.0,
                              child: GeneratedRectangle2Widget7(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 584.0,
                              right: null,
                              bottom: null,
                              width: 51.0,
                              height: 18.0,
                              child: GeneratedPriceWidget7(),
                            ),
                            Positioned(
                              left: 53.0,
                              top: 477.0,
                              right: null,
                              bottom: null,
                              width: 316.0,
                              height: 77.0,
                              child:
                                  GeneratedOurrichfullbodiedespressocombinedwithbittersweetmochasa1(),
                            ),
                            Positioned(
                              left: 132.0,
                              top: 410.0,
                              right: null,
                              bottom: null,
                              width: 157.0,
                              height: 26.0,
                              child: GeneratedEspressoWidget1(),
                            ),
                            Positioned(
                              left: 10.0,
                              top: 29.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 12.0,
                              child: GeneratedBackWidget17(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: -48.0,
                              right: null,
                              bottom: null,
                              width: 274.0,
                              height: 274.0,
                              child: GeneratedCoffeemainlogoWidget9(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 145.0,
                              right: null,
                              bottom: null,
                              width: 256.0,
                              height: 250.0,
                              child: GeneratedEspressoWidget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
